# https://supabase.com/docs/guides/cli/config
# Local Supabase config. Usado por `supabase start` cuando corras la stack
# localmente (opcional). El proyecto remoto se gestiona desde supabase.com.

project_id = "ph-plus"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false  # false en dev para facilitar testing
secure_password_change = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[edge_runtime]
enabled = true
policy = "oneshot"
inspector_port = 8083

[experimental]
orioledb_version = ""
