-- ─────────────────────────────────────────────────────────────────────────────
-- Catálogo REAL de PH PLUS (22 productos).
--
-- GENERADO AUTOMÁTICAMENTE — no editar a mano.
-- Fuente: app/lib/products.ts
-- Regenerar: npx tsx scripts/gen-products-seed.ts
--
-- Idempotente: upsert por slug. Se puede correr las veces que haga falta.
-- ─────────────────────────────────────────────────────────────────────────────

insert into public.products (
  slug, title, short_title, tagline, description, long_description, features, includes, price_value, prev_price_value, category, size, visual_key, popularity, highlight, badge, gallery, specs, usage, rating_average, rating_count, is_active, in_stock
) values
  (
    'kit-inicial-botellon-19lts',
    'Kit inicial de botellón 19 lts',
    'Kit inicial de
botellón 19 lts',
    'Empieza a hidratarte mejor desde el primer día',
    'Kit completo con botellón de 19 litros más dispensador manual. Ideal para hogares y oficinas que quieren empezar con PH PLUS. Agua alcalina PH 9, lista para servir.',
    '["El Kit inicial PH PLUS es la forma más cómoda de empezar a tomar agua alcalina en casa. Incluye un botellón de 19 litros sellado y un dispensador manual de presión, listos para usar desde el primer minuto.","Nuestra agua pasa por 14 procesos de filtración que la enriquecen con calcio y magnesio, manteniendo un pH estable de 9.0 para ayudarte a equilibrar tu cuerpo, mejorar la digestión y favorecer tu rendimiento durante el día.","Todos los envases son retornables y libres de BPA. Al pedir tu próxima recarga, recogemos el botellón vacío para reutilizarlo."]'::jsonb,
    '["Agua alcalina PH 9","Libre de BPA","Calcio y magnesio para tu bienestar","Dispensador manual incluido"]'::jsonb,
    '["1 botellón de 19 litros","1 dispensador manual","Guía de uso y mantenimiento"]'::jsonb,
    85000, null,
    'kit', '19L', 'kit',
    95, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Contenido","value":"19 litros + dispensador"},{"label":"Material del envase","value":"PET grado alimenticio, libre de BPA"},{"label":"Compatibilidad","value":"Cualquier dispensador estándar"},{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Retira el sello del botellón y voltea con cuidado sobre el dispensador.","Acciona la bomba manual unas veces para purgar el aire.","Sirve y disfruta. Reemplaza la recarga cuando se acabe.","Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 124,
    true, true
  ),
  (
    'promocion-garrafas',
    'Promoción Garrafas — ¡Pague 3, lleve 5!',
    '',
    'El plan más conveniente para mantener tu casa siempre hidratada',
    'Pagas 3 garrafas de PH PLUS y te llevas 5. Perfecto para familias que disfrutan agua alcalina todos los días, sin tener que pedir recargas tan seguido.',
    '["Con esta promoción consigues 5 garrafas selladas pagando solo 3. Un ahorro de más del 35% frente al precio individual, ideal para tener reservas en casa, en la oficina o para llevar al gimnasio.","Cada garrafa contiene agua PH PLUS con un pH estable de 9.0, embotellada el mismo día del despacho. El sellado garantiza la frescura hasta el momento de abrir.","Promoción por tiempo limitado. Sujeta a disponibilidad de inventario."]'::jsonb,
    '["5 garrafas selladas","PH 9 estable en cada garrafa","Ahorro de más del 35%","Disponible por tiempo limitado"]'::jsonb,
    '["5 garrafas PH PLUS","Envío incluido en zonas habilitadas"]'::jsonb,
    73470, 122450,
    'promocion', '1.5L', 'garrafas',
    90, true,
    '{"title":"PROMOCIÓN GARRAFAS","sub":"¡Pague 3, lleve 5!"}'::jsonb,
    '[{"visualKey":"garrafas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"garrafas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"garrafas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"garrafas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Cantidad","value":"5 garrafas"},{"label":"Tamaño individual","value":"1,5 litros"},{"label":"Total de agua","value":"7,5 litros"},{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva las garrafas selladas en lugar fresco.","Una vez abierta, mantén la garrafa refrigerada y consúmela en máximo 7 días.","Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.7, 89,
    true, true
  ),
  (
    'recargas-19lts',
    '2 recargas de botellón 19 lts',
    '2 recargas
cada una de 19 lts',
    'Mantén tu dispensador siempre lleno',
    'Dos recargas de 19 litros para clientes que ya tienen su botellón. Programación de entrega rápida en tu zona.',
    '["Diseñado para clientes que ya cuentan con un botellón y solo necesitan reponer su agua. Recibirás dos botellones de 19 litros sellados con agua alcalina PH 9.","Al momento de entregar las recargas, nuestro equipo recoge sin costo los botellones vacíos. Así contribuyes a reutilizar y reducir residuos plásticos.","Si quieres asegurar recepción periódica, puedes pasarte a la suscripción mensual con descuento adicional."]'::jsonb,
    '["2 botellones de 19 litros","Agua alcalina PH 9","Envío a domicilio","Programa recurrente disponible"]'::jsonb,
    '["2 recargas de 19 litros","Recolección de botellón vacío"]'::jsonb,
    69000, null,
    'recarga', '19L', 'recargas',
    80, false,
    null,
    '[{"visualKey":"recargas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"recargas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"recargas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"recargas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Cantidad","value":"2 botellones de 19 L"},{"label":"Total de agua","value":"38 litros"},{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.9, 156,
    true, true
  ),
  (
    'recarga-19lts-individual',
    '1 recarga de 19 lts',
    '1 recarga de 19 lts',
    'Una recarga cuando la necesites',
    'Recarga individual de 19 litros para reponer tu botellón. Ideal para hogares pequeños o pedidos puntuales.',
    '["Pide una sola recarga cuando la necesites, sin compromisos. Llega sellada el mismo día en zona urbana de Bogotá.","Nos llevamos el botellón vacío sin costo adicional al momento de entregar el nuevo."]'::jsonb,
    '["1 recarga de 19 litros","Agua alcalina PH 9","Entrega en menos de 24 h","Sin compromiso de suscripción"]'::jsonb,
    '["1 botellón sellado 19 lts","Recolección del vacío"]'::jsonb,
    50000, null,
    'recarga', '19L', 'recargas',
    70, false,
    null,
    '[{"visualKey":"recargas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"recargas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"recargas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"recargas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Contenido","value":"19 litros"},{"label":"Tipo","value":"Recarga retornable"},{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.7, 64,
    true, true
  ),
  (
    'botellon-19lts',
    'Botellón 19 lts (solo envase + agua)',
    'Botellón 19 lts',
    'El clásico de PH PLUS para tu dispensador',
    'Botellón retornable de 19 litros con agua alcalina PH 9. Para clientes que ya tienen dispensador en casa u oficina.',
    '["Botellón sellado de 19 litros, listo para tu dispensador. Diseñado para soportar el uso continuo en casa u oficina.","Forma parte de nuestro programa retornable: cuando pidas tu próxima recarga, recogemos sin costo el envase vacío."]'::jsonb,
    '["Envase reutilizable y certificado","Agua alcalina PH 9","Libre de BPA","Sellado al vacío"]'::jsonb,
    '["1 botellón de 19 litros sellado"]'::jsonb,
    42000, null,
    'botellon', '19L', 'kit',
    65, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Contenido","value":"19 litros"},{"label":"Material","value":"Policarbonato retornable"},{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.6, 42,
    true, true
  ),
  (
    'garrafa-1l-pack6',
    'Pack 6 garrafas de 1 litro',
    'Pack 6 × 1 L',
    'Perfectas para llevar al gym, la oficina o la universidad',
    'Seis garrafas individuales de 1 litro, cómodas de transportar. Ideales para mantenerte hidratado fuera de casa.',
    '["Diseñadas para quienes están en movimiento: van al gimnasio, oficina, universidad o entrenamientos al aire libre.","Cada garrafa de 1 litro mantiene el sello hermético hasta abrirla, garantizando frescura. Material reciclable, libre de BPA."]'::jsonb,
    '["6 garrafas de 1 litro","Tapa hermética","Agua alcalina PH 9","Material reciclable"]'::jsonb,
    '["6 garrafas PH PLUS de 1 litro"]'::jsonb,
    24000, null,
    'garrafa', '1L', 'garrafas',
    55, false,
    null,
    '[{"visualKey":"garrafas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"garrafas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"garrafas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"garrafas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Cantidad","value":"6 garrafas"},{"label":"Tamaño","value":"1 litro c/u"},{"label":"Total","value":"6 litros"},{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.7, 38,
    true, true
  ),
  (
    'garrafa-1-5l-pack6',
    'Pack 6 garrafas de 1,5 litros',
    'Pack 6 × 1,5 L',
    'Más agua, mismo precio cómodo',
    'Seis garrafas de 1,5 litros para el día a día. La presentación favorita de quienes necesitan más hidratación.',
    '["Pack ideal para quienes consumen 2 litros o más al día. Cada garrafa de 1,5 litros viene sellada y lista para guardar en la nevera.","Diseño compacto pensado para caber en cualquier mochila o cooler."]'::jsonb,
    '["6 garrafas de 1,5 litros","Agua alcalina PH 9","Tapa de seguridad","Etiqueta minimalista"]'::jsonb,
    '["6 garrafas PH PLUS de 1,5 litros"]'::jsonb,
    32000, null,
    'garrafa', '1.5L', 'garrafas',
    60, false,
    null,
    '[{"visualKey":"garrafas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"garrafas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"garrafas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"garrafas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Cantidad","value":"6 garrafas"},{"label":"Tamaño","value":"1,5 litros c/u"},{"label":"Total","value":"9 litros"},{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 47,
    true, true
  ),
  (
    'botellon-5l',
    'Botellón 5 litros',
    'Botellón 5 L',
    'El tamaño ideal para neveras y picnics',
    'Botellón de 5 litros, fácil de almacenar en la nevera o llevar a paseos. Listo para servir.',
    '["El formato 5 litros es perfecto cuando no necesitas un botellón grande pero quieres tener PH PLUS siempre a mano.","Lleva el agua a paseos, almuerzos familiares o tenla en la nevera del trabajo. Su asa integrada facilita el transporte."]'::jsonb,
    '["Envase de 5 litros","Tapa con asa","Agua alcalina PH 9","Caja troquelada para llevar"]'::jsonb,
    '["1 botellón sellado de 5 litros"]'::jsonb,
    12000, null,
    'botellon', '5L', 'kit',
    50, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Contenido","value":"5 litros"},{"label":"Asa","value":"Integrada en el envase"},{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.6, 29,
    true, true
  ),
  (
    'dispensador-manual',
    'Dispensador manual para botellón',
    'Dispensador manual',
    'Sirve tu agua sin esfuerzo',
    'Dispensador manual con bomba de presión, compatible con cualquier botellón de 19 litros. No requiere electricidad.',
    '["Dispensador con bomba de presión manual. No requiere electricidad, así que puedes usarlo en cualquier rincón de tu casa u oficina.","Tubo sumergible flexible, compatible con botellones estándar de 19 litros del mercado. Materiales libres de BPA."]'::jsonb,
    '["Bomba de presión manual","Compatible con botellones estándar","Sin electricidad","Materiales libres de BPA"]'::jsonb,
    '["1 dispensador manual","Manual de instalación"]'::jsonb,
    35000, null,
    'kit', 'kit', 'kit',
    45, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Tipo","value":"Bomba manual de presión"},{"label":"Materiales","value":"Plásticos libres de BPA"},{"label":"Compatibilidad","value":"Botellones 19 L estándar"}]'::jsonb,
    '["Inserta el tubo sumergible dentro del botellón sellado.","Aprieta firmemente la rosca o el seguro al cuello del botellón.","Acciona la bomba para purgar el aire y empezar a servir."]'::jsonb,
    4.5, 31,
    true, true
  ),
  (
    'dispensador-electrico',
    'Dispensador eléctrico frío / caliente',
    'Dispensador eléctrico',
    'Agua a la temperatura ideal en cualquier momento',
    'Dispensador eléctrico con doble grifería para agua fría y caliente. Diseño moderno, compatible con botellones de 19 litros.',
    '["Dispensador eléctrico premium con doble grifería: agua fría hasta 8°C y agua caliente hasta 90°C, ideal para té o café instantáneo.","Diseño compacto en blanco mate, encaja en cocinas y oficinas modernas. Garantía oficial de 12 meses."]'::jsonb,
    '["Agua fría y caliente","Compatible con botellones de 19 L","Indicadores LED","Garantía de 12 meses"]'::jsonb,
    '["1 dispensador eléctrico","Cable de alimentación","Manual"]'::jsonb,
    280000, null,
    'kit', 'kit', 'kit',
    40, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Voltaje","value":"110 V — 60 Hz"},{"label":"Potencia frío","value":"70 W"},{"label":"Potencia calor","value":"420 W"},{"label":"Capacidad","value":"Botellones 19 L estándar"},{"label":"Garantía","value":"12 meses"}]'::jsonb,
    '["Conecta a un tomacorriente con polo a tierra.","Coloca el botellón boca abajo sobre el receptáculo superior.","Espera 10 minutos antes del primer uso para que la temperatura se estabilice."]'::jsonb,
    4.6, 22,
    true, true
  ),
  (
    'suscripcion-mensual-4-botellones',
    'Suscripción mensual — 4 botellones de 19 L',
    'Suscripción mensual',
    'Cuatro botellones al mes, hidratación sin pensar',
    'Recibe automáticamente 4 botellones de 19 litros cada mes en tu casa u oficina. Cancela cuando quieras.',
    '["El plan favorito de familias y oficinas: cuatro botellones de 19 litros al mes con entrega programada. Te ahorras llamadas, pedidos y olvidos.","Recogemos los envases vacíos en cada entrega. Si necesitas más o menos botellones algún mes, puedes ajustarlo desde WhatsApp.","Cancela cuando quieras, sin penalización ni cláusula de permanencia."]'::jsonb,
    '["4 botellones cada mes","Ahorro frente a precio individual","Entrega programada","Sin cláusula de permanencia"]'::jsonb,
    '["4 recargas mensuales","Soporte prioritario"]'::jsonb,
    148000, 168000,
    'promocion', '19L', 'recargas',
    75, false,
    null,
    '[{"visualKey":"recargas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"recargas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"recargas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"recargas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"Frecuencia","value":"Mensual (4 botellones)"},{"label":"Total agua","value":"76 litros al mes"},{"label":"Permanencia","value":"Ninguna, cancela cuando quieras"},{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Define la fecha preferida de entrega al activar la suscripción.","Recogemos los envases vacíos en cada entrega siguiente.","Ajusta cantidades o pausa el plan desde WhatsApp."]'::jsonb,
    4.9, 51,
    true, true
  ),
  (
    'agua-ph-plus-kids-300ml-x24',
    'Agua PH PLUS KIDS 300 ml x 24 ud',
    'Agua PH PLUS KIDS 300 ml x 24 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS KIDS 300 ml x 24 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS KIDS 300 ml x 24 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS KIDS 300 ml x 24 ud"]'::jsonb,
    57600, null,
    'garrafa', '1L', 'garrafas',
    50, false,
    null,
    '[{"visualKey":"garrafas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"garrafas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"garrafas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"garrafas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  ),
  (
    'agua-ph-plus-300ml-x24',
    'Agua PH PLUS 300 ml x 24 ud',
    'Agua PH PLUS 300 ml x 24 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS 300 ml x 24 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS 300 ml x 24 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS 300 ml x 24 ud"]'::jsonb,
    57600, null,
    'garrafa', '1L', 'garrafas',
    50, false,
    null,
    '[{"visualKey":"garrafas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"garrafas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"garrafas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"garrafas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  ),
  (
    'agua-ph-plus-sport-500ml-x12',
    'Agua PH PLUS Sport 500 ml x 12 ud',
    'Agua PH PLUS Sport 500 ml x 12 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS Sport 500 ml x 12 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS Sport 500 ml x 12 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS Sport 500 ml x 12 ud"]'::jsonb,
    50160, null,
    'garrafa', '1L', 'kit',
    50, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  ),
  (
    'agua-ph-plus-500ml-x12',
    'Agua PH PLUS 500 ml x 12 ud',
    'Agua PH PLUS 500 ml x 12 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS 500 ml x 12 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS 500 ml x 12 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS 500 ml x 12 ud"]'::jsonb,
    48480, null,
    'garrafa', '1L', 'kit',
    50, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  ),
  (
    'agua-ph-plus-fit-1l-x6',
    'Agua PH PLUS FIT 1 L x 6 ud',
    'Agua PH PLUS FIT 1 L x 6 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS FIT 1 L x 6 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS FIT 1 L x 6 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS FIT 1 L x 6 ud"]'::jsonb,
    35376, 44220,
    'garrafa', '1L', 'garrafas',
    50, false,
    null,
    '[{"visualKey":"garrafas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"garrafas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"garrafas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"garrafas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  ),
  (
    'agua-ph-plus-1l-x6',
    'Agua PH PLUS 1 L x 6 ud',
    'Agua PH PLUS 1 L x 6 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS 1 L x 6 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS 1 L x 6 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS 1 L x 6 ud"]'::jsonb,
    50160, null,
    'garrafa', '1L', 'kit',
    50, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  ),
  (
    'agua-ph-plus-5l-x1',
    'Agua PH PLUS 5 L x 1 ud',
    'Agua PH PLUS 5 L x 1 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS 5 L x 1 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS 5 L x 1 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS 5 L x 1 ud"]'::jsonb,
    24490, null,
    'garrafa', '5L', 'kit',
    50, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  ),
  (
    'agua-ph-plus-vidrio-280ml-x24',
    'Agua PH PLUS vidrio 280 ml x 24 ud',
    'Agua PH PLUS vidrio 280 ml x 24 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS vidrio 280 ml x 24 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS vidrio 280 ml x 24 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS vidrio 280 ml x 24 ud"]'::jsonb,
    108000, null,
    'garrafa', '1L', 'kit',
    50, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  ),
  (
    'agua-ph-plus-vidrio-477ml-x24',
    'Agua PH PLUS vidrio 477 ml x 24 ud',
    'Agua PH PLUS vidrio 477 ml x 24 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS vidrio 477 ml x 24 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS vidrio 477 ml x 24 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS vidrio 477 ml x 24 ud"]'::jsonb,
    132000, null,
    'garrafa', '1L', 'kit',
    50, false,
    null,
    '[{"visualKey":"kit","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"kit","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"kit","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"kit","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  ),
  (
    'agua-ph-plus-hierbabuena-500ml-x12',
    'Agua PH PLUS hierbabuena 500 ml x 12 ud',
    'Agua PH PLUS hierbabuena 500 ml x 12 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS hierbabuena 500 ml x 12 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS hierbabuena 500 ml x 12 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS hierbabuena 500 ml x 12 ud"]'::jsonb,
    63600, null,
    'garrafa', '1L', 'garrafas',
    50, false,
    null,
    '[{"visualKey":"garrafas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"garrafas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"garrafas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"garrafas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  ),
  (
    'agua-ph-plus-limonaria-500ml-x12',
    'Agua PH PLUS limonaria 500 ml x 12 ud',
    'Agua PH PLUS limonaria 500 ml x 12 ud',
    'Hidratación PH PLUS para todos los días',
    'Agua PH PLUS limonaria 500 ml x 12 ud, disponible para compra directa y entrega a domicilio.',
    '["Agua PH PLUS limonaria 500 ml x 12 ud con agua PH PLUS alcalina y filtrada, lista para disfrutar."]'::jsonb,
    '["Agua alcalina PH 9","14 procesos de filtración","Envase libre de BPA"]'::jsonb,
    '["Agua PH PLUS limonaria 500 ml x 12 ud"]'::jsonb,
    63600, null,
    'garrafa', '1L', 'garrafas',
    50, false,
    null,
    '[{"visualKey":"garrafas","bg":"#f4f6fb","caption":"Vista principal"},{"visualKey":"garrafas","bg":"#eef0ff","caption":"Vista lateral"},{"visualKey":"garrafas","bg":"#e8f4fb","caption":"Detalle"},{"visualKey":"garrafas","bg":"#fafbfd","caption":"En contexto"}]'::jsonb,
    '[{"label":"pH del agua","value":"9.0 ± 0.3 (alcalina)"},{"label":"Origen","value":"Manantial Cundinamarca"},{"label":"Tratamiento","value":"14 procesos de filtración"},{"label":"Certificación","value":"INVIMA RSA 0030646-2024"},{"label":"Conservación","value":"Lugar fresco, lejos del sol directo"}]'::jsonb,
    '["Conserva el producto en un lugar fresco y seco, lejos de la luz directa.","Una vez abierto, refrigéralo y consúmelo idealmente en menos de 7 días.","Lava el dispensador/recipiente con agua limpia antes del primer uso."]'::jsonb,
    4.8, 24,
    true, true
  )
on conflict (slug) do update set
  title = excluded.title,
  short_title = excluded.short_title,
  tagline = excluded.tagline,
  description = excluded.description,
  long_description = excluded.long_description,
  features = excluded.features,
  includes = excluded.includes,
  price_value = excluded.price_value,
  prev_price_value = excluded.prev_price_value,
  category = excluded.category,
  size = excluded.size,
  visual_key = excluded.visual_key,
  popularity = excluded.popularity,
  highlight = excluded.highlight,
  badge = excluded.badge,
  gallery = excluded.gallery,
  specs = excluded.specs,
  usage = excluded.usage,
  rating_average = excluded.rating_average,
  rating_count = excluded.rating_count,
  is_active = excluded.is_active,
  in_stock = excluded.in_stock,
  updated_at = timezone('utc', now());

-- Inventario inicial SÓLO para productos que todavía no tienen SKU asignado.
-- No toca los SKUs curados a mano en seed.sql.
insert into public.stock_items (sku, product_slug, current, low)
select 'SKU-' || upper(p.slug), p.slug, 50, 10
from public.products p
where not exists (
  select 1 from public.stock_items s where s.product_slug = p.slug
)
on conflict (sku) do nothing;
