-- =============================================================================
-- PH PLUS — Seed demo: catálogo extendido (22 productos adicionales)
-- =============================================================================
-- Idempotente: usa `on conflict (slug) do nothing`, se puede re-aplicar sin
-- duplicar filas. Llena el catálogo a 33+ productos para demos de cliente.
--
-- Nota sobre enums:
--   product_size soporta: '1L' | '1.5L' | '5L' | '19L' | 'kit'
--   Los "botellones" de 10/15/20 L se mapean al enum válido más cercano
--   (19L para botellones grandes, 5L para medianos, 'kit' para accesorios).
--   El tamaño "real" se refleja en el título, specs y description.
-- =============================================================================

insert into public.products (
  slug, title, short_title, tagline, description, long_description,
  features, includes, price_value, prev_price_value,
  category, size, visual_key, popularity, highlight, badge,
  gallery, specs, usage, rating_average, rating_count,
  is_active, in_stock, meta_title, meta_description
) values
  -- ---------------------------------------------------------------------------
  -- 1. BOTELLONES (5)
  -- ---------------------------------------------------------------------------
  (
    'botellon-10l',
    'Botellón 10 litros retornable',
    'Botellón 10L',
    'El intermedio perfecto entre 5L y 19L',
    'Botellón retornable de 10 litros con asa ergonómica, ideal para hogares pequeños o oficinas con poco espacio.',
    '["Botellón retornable de 10 litros con agua alcalina pH 9.0.", "Diseño ergonómico con asa reforzada para fácil transporte.", "Tapa hermética con sello de seguridad.", "Reutilizable hasta 50 veces — más ecológico que las botellas individuales."]'::jsonb,
    '["Asa ergonómica reforzada", "Tapa hermética con sello", "Plástico BPA-free", "Retornable y reutilizable"]'::jsonb,
    '["1 botellón de 10 litros", "Sello de garantía PH PLUS"]'::jsonb,
    24000, null,
    'botellon', '5L', 'kit', 58, false,
    null,
    '[]'::jsonb,
    '[{"label":"Capacidad","value":"10 litros"},{"label":"pH","value":"9.0"},{"label":"Material","value":"PET BPA-free"},{"label":"Peso vacío","value":"380 g"}]'::jsonb,
    '["Ideal para apartamentos pequeños.","Perfecto para oficinas con 2-3 personas.","Más fácil de cargar que el 19L."]'::jsonb,
    4.5, 7, true, true,
    'Botellón 10 litros agua alcalina pH 9.0 | PH PLUS',
    'Botellón retornable de 10 litros con agua alcalina pH 9.0. Asa ergonómica, BPA-free. Envío en Bogotá en 1-2 días.'
  ),
  (
    'botellon-15l-empresarial',
    'Botellón 15 litros empresarial',
    'Botellón 15L empresa',
    'La hidratación de tu equipo, sin interrupciones',
    'Botellón de 15 litros pensado para oficinas medianas. Compatible con todos los dispensadores estándar del mercado.',
    '["Diseñado para empresas con consumo medio-alto de agua.","Ahorra hasta 30% frente al consumo individual de botellas.","Compatible con dispensadores Top Loading universales.","Servicio empresarial con facturación electrónica DIAN."]'::jsonb,
    '["Cuello universal para dispensadores","Plástico reforzado de larga vida","Etiqueta con lote y fecha de envasado","Facturación electrónica disponible"]'::jsonb,
    '["1 botellón de 15 litros", "Etiqueta de lote y trazabilidad"]'::jsonb,
    34000, null,
    'botellon', '19L', 'kit', 62, false,
    null,
    '[]'::jsonb,
    '[{"label":"Capacidad","value":"15 litros"},{"label":"pH","value":"9.0"},{"label":"Cuello","value":"55 mm universal"},{"label":"Vida útil","value":"40 ciclos"}]'::jsonb,
    '["Recomendado para oficinas de 5-10 personas.","Cambia el botellón aproximadamente cada 7-10 días.","Solicita factura electrónica al hacer el pedido."]'::jsonb,
    4.6, 11, true, true,
    'Botellón 15L empresarial agua alcalina | PH PLUS',
    'Botellón empresarial de 15 litros con agua alcalina pH 9.0. Facturación electrónica DIAN. Ideal para oficinas.'
  ),
  (
    'botellon-20l-premium',
    'Botellón 20 litros Premium Oro',
    'Botellón 20L Premium',
    'Nuestro botellón más grande, con tapa dorada de edición especial',
    'Botellón premium de 20 litros con tapa dorada antifugas y certificación de mineralización extendida. Pensado para amantes del agua de alta gama.',
    '["Edición especial con tapa metalizada dorada antifugas.","Agua alcalina pH 9.2 con magnesio y calcio adicional.","Botellón fabricado en Tritan™ libre de microplásticos.","Incluye certificado de análisis fisicoquímico por lote."]'::jsonb,
    '["Tapa dorada antifugas premium","Mineralización extendida (Mg + Ca)","Material Tritan™ ultra resistente","Certificado de análisis por lote"]'::jsonb,
    '["1 botellón Premium de 20 litros","Tapa dorada de edición especial","Certificado de análisis fisicoquímico"]'::jsonb,
    58000, 72000,
    'botellon', '19L', 'kit', 70, true,
    '{"title":"EDICIÓN PREMIUM","sub":"Tapa dorada incluida"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Capacidad","value":"20 litros"},{"label":"pH","value":"9.2"},{"label":"Material","value":"Tritan™"},{"label":"Tapa","value":"Dorada antifugas"}]'::jsonb,
    '["Servir frío para realzar minerales.","Ideal como regalo corporativo.","Conservar el certificado para auditorías de calidad."]'::jsonb,
    4.9, 14, true, true,
    'Botellón 20L Premium Oro pH 9.2 | PH PLUS',
    'Botellón Premium 20 litros con tapa dorada y mineralización extendida. pH 9.2. Edición especial PH PLUS.'
  ),
  (
    'botellon-19l-sabor-frutal',
    'Botellón 19L sabor frutal (mango / maracuyá)',
    'Botellón 19L frutal',
    'Hidratación con un toque de sabor natural',
    'Botellón de 19 litros con infusión natural de fruta tropical. Endulzado únicamente con estevia, sin azúcares añadidos.',
    '["Infusión 100% natural de mango y maracuyá colombianos.","Endulzado sólo con estevia — 0 calorías añadidas.","Mantiene los beneficios alcalinos del agua base pH 9.0.","Disponible mientras dure la temporada de cosecha."]'::jsonb,
    '["Infusión natural de fruta","Endulzado con estevia","0 azúcares añadidos","Temporada limitada"]'::jsonb,
    '["1 botellón de 19 litros sabor frutal", "Etiqueta de edición limitada"]'::jsonb,
    52000, null,
    'botellon', '19L', 'kit', 48, false,
    '{"title":"TEMPORADA","sub":"Edición limitada"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Capacidad","value":"19 litros"},{"label":"pH","value":"9.0"},{"label":"Sabor","value":"Mango / Maracuyá"},{"label":"Endulzante","value":"Estevia natural"}]'::jsonb,
    '["Servir bien frío.","Agitar suavemente antes de usar.","Consumir en máximo 14 días después de abrir."]'::jsonb,
    4.4, 19, true, false,
    'Botellón 19L sabor frutal estevia | PH PLUS',
    'Botellón de 19 litros con infusión natural de mango y maracuyá. Endulzado con estevia. Temporada limitada.'
  ),
  (
    'kit-19l-kids',
    'Kit 19L Kids con dispensador infantil',
    'Kit 19L Kids',
    'Hidratación divertida y segura para los más pequeños',
    'Kit completo con botellón de 19 litros, dispensador infantil de colores con grifo a baja altura y vasos reutilizables.',
    '["Dispensador diseñado a altura de niños (40 cm).","Grifo de seguridad antigoteo y antiquemaduras (solo frío).","Botellón 19L con agua alcalina pH 9.0 ideal para crecimiento.","Incluye 4 vasos reutilizables con tapa antiderrame."]'::jsonb,
    '["Dispensador a baja altura","Grifo de seguridad antigoteo","Vasos antiderrame incluidos","Solo agua fría (sin riesgo de quemaduras)"]'::jsonb,
    '["1 botellón 19L","1 dispensador infantil de colores","4 vasos antiderrame 250 ml","Stickers decorativos"]'::jsonb,
    135000, 155000,
    'kit', '19L', 'kit', 67, true,
    '{"title":"FAVORITO FAMILIAS","sub":"Diseño infantil"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Altura dispensador","value":"40 cm"},{"label":"Capacidad botellón","value":"19 litros"},{"label":"Vasos","value":"4 x 250 ml"},{"label":"Edad recomendada","value":"+3 años"}]'::jsonb,
    '["Supervisar a niños menores de 5 años.","Lavar vasos con agua tibia y jabón neutro.","Recargar el botellón cuando llegue a 1/4 de capacidad."]'::jsonb,
    4.8, 22, true, true,
    'Kit 19L Kids dispensador infantil | PH PLUS',
    'Kit familiar con botellón 19L, dispensador infantil de seguridad y 4 vasos antiderrame. Para niños desde 3 años.'
  ),
  -- ---------------------------------------------------------------------------
  -- 2. GARRAFAS PREMIUM (4)
  -- ---------------------------------------------------------------------------
  (
    'garrafa-pepino-1l',
    'Garrafa 1L infusión de pepino',
    'Garrafa pepino 1L',
    'Frescura natural en cada sorbo',
    'Garrafa de 1 litro con infusión real de pepino orgánico. Refrescante, hidratante y con propiedades detox.',
    '["Pepino orgánico cultivado en Boyacá.","Sin azúcares ni conservantes.","Ideal post-entreno o para días calurosos.","Botella reutilizable de vidrio templado."]'::jsonb,
    '["Pepino orgánico de Boyacá","Sin azúcares ni conservantes","Botella de vidrio templado","Tapa de bambú natural"]'::jsonb,
    '["1 garrafa de vidrio 1L con infusión"]'::jsonb,
    14500, null,
    'garrafa', '1L', 'garrafas', 42, false,
    null,
    '[]'::jsonb,
    '[{"label":"Capacidad","value":"1 litro"},{"label":"Infusión","value":"Pepino orgánico"},{"label":"Material","value":"Vidrio templado"},{"label":"Origen","value":"Boyacá"}]'::jsonb,
    '["Mantener refrigerado.","Consumir en 7 días tras abrir.","Recargar con agua filtrada para una segunda infusión."]'::jsonb,
    4.6, 9, true, true,
    'Garrafa 1L pepino orgánico detox | PH PLUS',
    'Garrafa de vidrio 1L con infusión de pepino orgánico de Boyacá. Sin azúcares, ideal detox post-entreno.'
  ),
  (
    'garrafa-limon-1l',
    'Garrafa 1L infusión de limón Tahití',
    'Garrafa limón 1L',
    'Cítrico, brillante, con todas las vitaminas',
    'Garrafa de 1 litro con infusión de limón Tahití fresco. Aporta vitamina C natural y un toque ácido refrescante.',
    '["Limón Tahití cultivado en el Tolima.","Rica en vitamina C natural.","Sin endulzantes — el sabor ácido lo aporta la fruta.","Botella reutilizable y reciclable."]'::jsonb,
    '["Limón Tahití del Tolima","Vitamina C natural","Sin endulzantes añadidos","Vidrio templado reutilizable"]'::jsonb,
    '["1 garrafa de vidrio 1L con infusión de limón"]'::jsonb,
    14500, null,
    'garrafa', '1L', 'garrafas', 44, false,
    null,
    '[]'::jsonb,
    '[{"label":"Capacidad","value":"1 litro"},{"label":"Infusión","value":"Limón Tahití"},{"label":"Vitamina C","value":"~30 mg/L"},{"label":"Origen","value":"Tolima"}]'::jsonb,
    '["Ideal en ayunas para activar el metabolismo.","Servir con hielo y hojas de menta.","Consumir en 5 días tras abrir."]'::jsonb,
    4.7, 13, true, true,
    'Garrafa 1L limón Tahití vitamina C | PH PLUS',
    'Garrafa de vidrio 1L con infusión de limón Tahití del Tolima. Vitamina C natural, sin endulzantes.'
  ),
  (
    'garrafa-jengibre-1l',
    'Garrafa 1L infusión de jengibre',
    'Garrafa jengibre 1L',
    'Energía y digestión en una sola botella',
    'Garrafa de 1 litro con jengibre fresco rallado. Apoya la digestión, da energía y refuerza las defensas.',
    '["Jengibre fresco del Quindío.","Beneficios digestivos y antiinflamatorios.","Toque levemente picante natural.","Botella reutilizable de vidrio."]'::jsonb,
    '["Jengibre fresco del Quindío","Apoya la digestión","Antiinflamatorio natural","Vidrio templado premium"]'::jsonb,
    '["1 garrafa de vidrio 1L con infusión de jengibre"]'::jsonb,
    16000, null,
    'garrafa', '1L', 'garrafas', 38, false,
    null,
    '[]'::jsonb,
    '[{"label":"Capacidad","value":"1 litro"},{"label":"Infusión","value":"Jengibre fresco"},{"label":"Sabor","value":"Levemente picante"},{"label":"Origen","value":"Quindío"}]'::jsonb,
    '["Tomar 1 vaso antes de las comidas.","No recomendado para mujeres embarazadas sin consulta médica.","Mantener refrigerado."]'::jsonb,
    4.5, 8, true, true,
    'Garrafa 1L jengibre digestión natural | PH PLUS',
    'Garrafa de vidrio 1L con infusión de jengibre fresco del Quindío. Apoya la digestión y las defensas.'
  ),
  (
    'garrafa-menta-1l',
    'Garrafa 1.5L infusión de menta',
    'Garrafa menta 1.5L',
    'Refrescante, relajante, perfecta para el verano',
    'Garrafa de 1.5 litros con hojas frescas de menta colombiana. Sabor refrescante con propiedades digestivas y relajantes.',
    '["Menta orgánica cultivada en Cundinamarca.","Efecto refrescante natural.","Apoya la digestión y reduce el estrés.","Tamaño familiar 1.5L."]'::jsonb,
    '["Menta orgánica de Cundinamarca","Sabor refrescante natural","Tamaño familiar 1.5L","Tapa hermética de bambú"]'::jsonb,
    '["1 garrafa de vidrio 1.5L con infusión de menta"]'::jsonb,
    19000, 22000,
    'garrafa', '1.5L', 'garrafas', 46, true,
    null,
    '[]'::jsonb,
    '[{"label":"Capacidad","value":"1.5 litros"},{"label":"Infusión","value":"Menta fresca"},{"label":"Origen","value":"Cundinamarca"},{"label":"Tapa","value":"Bambú natural"}]'::jsonb,
    '["Servir muy fría con hielo.","Excelente acompañante de comidas pesadas.","Reutilizar la botella con agua filtrada."]'::jsonb,
    4.8, 17, true, true,
    'Garrafa 1.5L menta fresca colombiana | PH PLUS',
    'Garrafa de vidrio 1.5L con infusión de menta orgánica de Cundinamarca. Refrescante y digestiva.'
  ),
  -- ---------------------------------------------------------------------------
  -- 3. RECARGAS EN PACK (3)
  -- ---------------------------------------------------------------------------
  (
    'pack-4-recargas',
    'Pack 4 recargas de botellón 19L',
    'Pack 4 recargas',
    'Cuatro botellones al mejor precio',
    'Cuatro recargas de botellón 19L. Ideal para hogares de 2 personas durante un mes.',
    '["4 recargas de 19 litros (76 L totales).","Precio por recarga ~15% menor que individual.","Programa la entrega cada 7 días.","Requiere botellón retornable PH PLUS."]'::jsonb,
    '["15% de descuento por volumen","Programación de entregas","Botellones retornables","Agua alcalina pH 9.0"]'::jsonb,
    '["4 botellones de 19L (sólo agua, requiere envase)"]'::jsonb,
    132000, 144000,
    'recarga', '19L', 'recargas', 75, true,
    '{"title":"AHORRA 15%","sub":"Pack mensual"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Total litros","value":"76 L"},{"label":"Recargas","value":"4"},{"label":"Ahorro","value":"~15%"},{"label":"Frecuencia sugerida","value":"Cada 7 días"}]'::jsonb,
    '["Tener al menos 1 botellón retornable disponible.","Coordinar entregas cada 7-10 días.","Lavar el dispensador entre cambios."]'::jsonb,
    4.7, 24, true, true,
    'Pack 4 recargas 19L ahorro mensual | PH PLUS',
    'Pack mensual de 4 recargas de botellón 19L con 15% de descuento. Programación de entregas en Bogotá.'
  ),
  (
    'pack-8-recargas',
    'Pack 8 recargas de botellón 19L',
    'Pack 8 recargas',
    'Dos meses de agua alcalina sin pensar',
    'Ocho recargas de botellón 19L con descuento progresivo. Perfecto para familias de 3-4 personas.',
    '["8 recargas de 19 litros (152 L totales).","Descuento del 20% frente al precio individual.","Programa hasta 2 meses de entregas.","Soporte preferente vía WhatsApp."]'::jsonb,
    '["20% de descuento por volumen","Hasta 2 meses programados","Soporte WhatsApp preferente","Cambio de botellón en cada entrega"]'::jsonb,
    '["8 botellones de 19L (sólo agua)"]'::jsonb,
    248000, 288000,
    'recarga', '19L', 'recargas', 78, true,
    '{"title":"AHORRA 20%","sub":"Pack bimestral"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Total litros","value":"152 L"},{"label":"Recargas","value":"8"},{"label":"Ahorro","value":"~20%"},{"label":"Duración estimada","value":"2 meses"}]'::jsonb,
    '["Recomendado para 3-4 personas.","Programar entregas cada 7-8 días.","Conservar botellones en lugar fresco."]'::jsonb,
    4.8, 31, true, true,
    'Pack 8 recargas 19L bimestral | PH PLUS',
    'Pack bimestral de 8 recargas de botellón 19L con 20% de descuento. Soporte preferente PH PLUS.'
  ),
  (
    'pack-12-recargas',
    'Pack 12 recargas de botellón 19L',
    'Pack 12 recargas',
    'Tres meses cubiertos al mejor precio del año',
    'Doce recargas de botellón 19L con el máximo descuento. Ideal para familias grandes u oficinas pequeñas.',
    '["12 recargas de 19 litros (228 L totales).","Descuento del 25% — el más alto del catálogo.","Programa hasta 3 meses de entregas.","Acceso a cupón exclusivo para próximas compras."]'::jsonb,
    '["25% de descuento máximo","Hasta 3 meses programados","Cupón exclusivo posventa","Cambio de botellón en cada entrega"]'::jsonb,
    '["12 botellones de 19L (sólo agua)","Cupón PHPLUS5K para tu próxima compra"]'::jsonb,
    324000, 432000,
    'recarga', '19L', 'recargas', 82, true,
    '{"title":"MEJOR PRECIO","sub":"Ahorra 25%"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Total litros","value":"228 L"},{"label":"Recargas","value":"12"},{"label":"Ahorro","value":"~25%"},{"label":"Duración estimada","value":"3 meses"}]'::jsonb,
    '["Recomendado para 4-5 personas u oficinas pequeñas.","Programar entregas semanales.","Conservar el cupón PHPLUS5K para próxima compra."]'::jsonb,
    4.9, 38, true, true,
    'Pack 12 recargas 19L trimestral | PH PLUS',
    'Pack trimestral de 12 recargas de botellón 19L con 25% de descuento y cupón exclusivo PH PLUS.'
  ),
  -- ---------------------------------------------------------------------------
  -- 4. KITS Y ACCESORIOS (5)
  -- ---------------------------------------------------------------------------
  (
    'kit-oficina-completo',
    'Kit oficina completo (dispensador + 2 botellones + vasos)',
    'Kit oficina',
    'Todo lo que tu oficina necesita para hidratarse',
    'Kit empresarial con dispensador eléctrico, 2 botellones de 19L y 20 vasos reutilizables. Listo para instalar.',
    '["Dispensador eléctrico frío/caliente con compresor silencioso.","2 botellones de 19L con agua alcalina pH 9.0.","20 vasos reutilizables de 200 ml con logo PH PLUS.","Garantía de 12 meses en dispensador."]'::jsonb,
    '["Dispensador eléctrico silencioso","Frío y caliente programable","20 vasos con logo","Garantía 12 meses"]'::jsonb,
    '["1 dispensador eléctrico","2 botellones 19L","20 vasos reutilizables","Manual + factura DIAN"]'::jsonb,
    489000, 545000,
    'kit', 'kit', 'kit', 56, true,
    '{"title":"AHORRO EMPRESARIAL","sub":"Listo para instalar"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Dispensador","value":"Eléctrico frío/caliente"},{"label":"Botellones","value":"2 x 19L"},{"label":"Vasos","value":"20 unidades"},{"label":"Garantía","value":"12 meses"}]'::jsonb,
    '["Instalación incluida en Bogotá.","Conectar a corriente 110V.","Programar mantenimiento cada 6 meses."]'::jsonb,
    4.8, 9, true, true,
    'Kit oficina dispensador + 2 botellones | PH PLUS',
    'Kit empresarial completo con dispensador eléctrico frío/caliente, 2 botellones 19L y 20 vasos. Garantía 12 meses.'
  ),
  (
    'kit-gym-deportistas',
    'Kit gym para deportistas (shaker + 4 garrafas)',
    'Kit gym',
    'Hidratación pensada para tu rutina de entrenamiento',
    'Kit deportivo con shaker de 700 ml, 4 garrafas de 1L y una toalla microfibra. Diseñado para gymers y runners.',
    '["Shaker con malla mezcladora interna.","4 garrafas de 1L con tapa deportiva.","Toalla microfibra de secado rápido.","Bolsa de transporte impermeable."]'::jsonb,
    '["Shaker con malla mezcladora","Garrafas con tapa deportiva","Toalla microfibra incluida","Bolsa impermeable"]'::jsonb,
    '["1 shaker 700ml","4 garrafas 1L","1 toalla microfibra","1 bolsa impermeable"]'::jsonb,
    72000, null,
    'kit', '1L', 'garrafas', 51, false,
    null,
    '[]'::jsonb,
    '[{"label":"Shaker","value":"700 ml con malla"},{"label":"Garrafas","value":"4 x 1L"},{"label":"Toalla","value":"Microfibra 40x80 cm"},{"label":"Bolsa","value":"Impermeable"}]'::jsonb,
    '["Lavar shaker tras cada uso.","Ideal para llevar al gym o trote matutino.","Usar agua alcalina PH PLUS para optimizar recuperación."]'::jsonb,
    4.6, 12, true, true,
    'Kit gym shaker + 4 garrafas | PH PLUS',
    'Kit deportivo PH PLUS: shaker 700ml, 4 garrafas 1L, toalla microfibra y bolsa impermeable.'
  ),
  (
    'kit-familia-mensual',
    'Kit familia mensual (dispensador + 4 recargas)',
    'Kit familia mensual',
    'Un mes completo de hidratación familiar',
    'Kit ideal para familias de 4-5 personas: dispensador manual de alta presión + 4 recargas de botellón 19L.',
    '["Dispensador manual de alta presión.","4 recargas de 19L (76 L totales).","Cobertura aproximada de 1 mes para familia de 4.","Programación de entregas incluida."]'::jsonb,
    '["Dispensador manual sin electricidad","4 recargas programadas","Cobertura mensual familiar","Sin compromiso de permanencia"]'::jsonb,
    '["1 dispensador manual","4 recargas 19L","Cronograma de entregas"]'::jsonb,
    178000, 198000,
    'kit', '19L', 'kit', 64, true,
    '{"title":"PLAN FAMILIA","sub":"30 días de agua"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Dispensador","value":"Manual de alta presión"},{"label":"Recargas","value":"4 x 19L"},{"label":"Duración","value":"~30 días"},{"label":"Personas","value":"4-5"}]'::jsonb,
    '["Lavar el dispensador semanalmente.","Programar entregas cada 7 días.","Mantener botellones en lugar fresco y oscuro."]'::jsonb,
    4.7, 16, true, true,
    'Kit familia mensual dispensador + 4 recargas | PH PLUS',
    'Kit mensual familiar con dispensador manual y 4 recargas 19L. Cobertura para 4-5 personas durante 30 días.'
  ),
  (
    'bomba-electrica-usb',
    'Bomba eléctrica USB para botellón',
    'Bomba USB',
    'Sirve agua con un botón, carga por USB',
    'Bomba eléctrica recargable por USB-C. Compatible con botellones de 5L, 10L, 15L y 19L. Hasta 30 días de uso por carga.',
    '["Carga USB-C completa en 3 horas.","Hasta 30 días de uso por carga (3-4 servidas/día).","Compatible con cualquier botellón estándar.","Silenciosa: 45 dB en operación."]'::jsonb,
    '["Recargable USB-C","Hasta 30 días por carga","Compatible 5L a 19L","Operación silenciosa"]'::jsonb,
    '["1 bomba eléctrica","Cable USB-C","Tubo extensible","Instructivo"]'::jsonb,
    48000, null,
    'kit', 'kit', 'kit', 53, false,
    null,
    '[]'::jsonb,
    '[{"label":"Carga","value":"USB-C 3h"},{"label":"Autonomía","value":"~30 días"},{"label":"Ruido","value":"45 dB"},{"label":"Compatibilidad","value":"Botellones 5L-19L"}]'::jsonb,
    '["Cargar completamente antes del primer uso.","Limpiar el tubo extensible mensualmente.","No sumergir la bomba en agua."]'::jsonb,
    4.5, 18, true, true,
    'Bomba eléctrica USB para botellón | PH PLUS',
    'Bomba recargable USB-C para botellones 5L a 19L. Hasta 30 días de uso por carga. Operación silenciosa.'
  ),
  (
    'soporte-botellon-acero',
    'Soporte de acero inoxidable para botellón',
    'Soporte acero',
    'Eleva tu botellón con estilo y estabilidad',
    'Soporte de acero inoxidable cepillado, compatible con botellones de 5L a 19L. Diseño minimalista para cocinas modernas.',
    '["Acero inoxidable 304 grado alimenticio.","Base antideslizante con tope de goma.","Soporta hasta 25 kg.","Diseño minimalista que combina con cualquier cocina."]'::jsonb,
    '["Acero inoxidable 304","Base antideslizante","Capacidad 25 kg","Diseño minimalista"]'::jsonb,
    '["1 soporte de acero","4 patas antideslizantes"]'::jsonb,
    38000, null,
    'kit', 'kit', 'kit', 41, false,
    null,
    '[]'::jsonb,
    '[{"label":"Material","value":"Acero inoxidable 304"},{"label":"Capacidad","value":"25 kg máx"},{"label":"Altura","value":"35 cm"},{"label":"Diámetro","value":"28 cm"}]'::jsonb,
    '["Ubicar sobre superficie nivelada.","Limpiar con paño húmedo y secar.","No usar productos abrasivos."]'::jsonb,
    4.4, 6, true, false,
    'Soporte acero inoxidable para botellón | PH PLUS',
    'Soporte minimalista de acero inoxidable 304 para botellones de 5L a 19L. Capacidad 25 kg.'
  ),
  -- ---------------------------------------------------------------------------
  -- 5. PROMOS DE TEMPORADA (3)
  -- ---------------------------------------------------------------------------
  (
    'promo-dia-del-padre',
    'Promo Día del Padre — Botellón Premium + dispensador',
    'Promo Día del Padre',
    'El regalo perfecto para los papás conscientes',
    'Combo de edición especial Día del Padre: 1 botellón Premium 20L tapa dorada + dispensador eléctrico + tarjeta dedicatoria.',
    '["Botellón Premium 20L con tapa dorada.","Dispensador eléctrico frío/caliente.","Empaque de regalo con cinta dorada.","Tarjeta de dedicatoria personalizable."]'::jsonb,
    '["Empaque de regalo incluido","Tarjeta personalizable","Edición limitada","Disponible hasta agotar"]'::jsonb,
    '["1 botellón Premium 20L","1 dispensador eléctrico","1 empaque regalo","1 tarjeta personalizable"]'::jsonb,
    349000, 399000,
    'promocion', 'kit', 'kit', 35, true,
    '{"title":"DÍA DEL PADRE","sub":"Edición especial"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Botellón","value":"Premium 20L dorado"},{"label":"Dispensador","value":"Eléctrico frío/caliente"},{"label":"Empaque","value":"Regalo premium"},{"label":"Vigencia","value":"Hasta junio 21"}]'::jsonb,
    '["Pedir con 5 días de anticipación para empaque personalizado.","Incluir mensaje de dedicatoria al hacer el pedido.","Promoción no acumulable con otros cupones."]'::jsonb,
    4.7, 5, true, true,
    'Promo Día del Padre botellón Premium + dispensador | PH PLUS',
    'Combo Día del Padre: botellón Premium 20L tapa dorada + dispensador eléctrico + empaque regalo personalizable.'
  ),
  (
    'promo-dia-de-la-madre',
    'Promo Día de la Madre — Garrafas infusión x4 + flores',
    'Promo Día de la Madre',
    'Hidratación con cariño para la mejor mamá',
    'Combo especial Día de la Madre: 4 garrafas con infusiones premium (pepino, limón, jengibre, menta) + arreglo floral fresco.',
    '["4 garrafas con infusiones naturales premium.","Arreglo floral fresco coordinado con artesano local.","Empaque sustentable con tarjeta de dedicatoria.","Entrega coordinada para llegar el día exacto."]'::jsonb,
    '["4 infusiones premium","Arreglo floral fresco","Empaque sustentable","Entrega en fecha solicitada"]'::jsonb,
    '["4 garrafas con infusión","1 arreglo floral","1 tarjeta personalizable","Empaque sustentable"]'::jsonb,
    159000, 189000,
    'promocion', '1L', 'garrafas', 37, true,
    '{"title":"DÍA DE LA MADRE","sub":"Con flores incluidas"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Garrafas","value":"4 infusiones"},{"label":"Flores","value":"Arreglo fresco local"},{"label":"Empaque","value":"Sustentable"},{"label":"Vigencia","value":"Hasta mayo 15"}]'::jsonb,
    '["Pedir con 3 días de anticipación.","Especificar dirección de entrega y fecha exacta.","Las flores varían según disponibilidad de temporada."]'::jsonb,
    4.9, 11, true, true,
    'Promo Día de la Madre garrafas + flores | PH PLUS',
    'Combo especial Día de la Madre: 4 garrafas con infusión premium + arreglo floral fresco con dedicatoria.'
  ),
  (
    'promo-pack-navideno',
    'Promo Pack Navideño — Kit familia + sorpresas',
    'Pack Navideño',
    'La hidratación más cálida de la temporada',
    'Pack navideño con dispensador manual, 6 recargas 19L, 2 garrafas premium y caja de chocolates artesanales colombianos.',
    '["6 recargas 19L para todo diciembre.","Dispensador manual de alta presión.","2 garrafas con infusión (menta + limón).","Caja de chocolates artesanales del Cauca."]'::jsonb,
    '["Pack navideño completo","Chocolates artesanales incluidos","Empaque festivo","Edición de temporada"]'::jsonb,
    '["1 dispensador manual","6 recargas 19L","2 garrafas infusión","1 caja chocolates artesanales"]'::jsonb,
    289000, 359000,
    'promocion', '19L', 'kit', 49, true,
    '{"title":"NAVIDAD PH PLUS","sub":"Pack festivo"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Recargas","value":"6 x 19L"},{"label":"Garrafas","value":"2 infusión premium"},{"label":"Chocolates","value":"Caja artesanal Cauca"},{"label":"Vigencia","value":"1-23 diciembre"}]'::jsonb,
    '["Pedir antes del 18 de diciembre para entrega navideña.","Empaque festivo de regalo incluido.","Promoción no acumulable con suscripciones activas."]'::jsonb,
    4.8, 7, true, true,
    'Promo Pack Navideño kit familia + chocolates | PH PLUS',
    'Pack navideño con dispensador manual, 6 recargas 19L, garrafas premium y chocolates artesanales colombianos.'
  ),
  -- ---------------------------------------------------------------------------
  -- 6. SUSCRIPCIONES (2)
  -- ---------------------------------------------------------------------------
  (
    'suscripcion-semanal',
    'Suscripción semanal — 1 botellón 19L cada 7 días',
    'Suscripción semanal',
    'Hidratación constante, cobro automático cada semana',
    'Recibe 1 botellón de 19L cada 7 días con 10% de descuento permanente. Pausa o cancela cuando quieras.',
    '["1 botellón 19L cada semana, sin pensar.","10% de descuento permanente.","Pausa o cancela desde Mi Cuenta.","Cargo automático cada lunes."]'::jsonb,
    '["10% descuento permanente","Entrega semanal automática","Pausa flexible","Sin permanencia mínima"]'::jsonb,
    '["1 botellón 19L semanal","Acceso al panel de suscripciones"]'::jsonb,
    37800, null,
    'promocion', '19L', 'recargas', 58, false,
    '{"title":"SUSCRIPCIÓN","sub":"-10% siempre"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Frecuencia","value":"Cada 7 días"},{"label":"Descuento","value":"10% permanente"},{"label":"Cobro","value":"Lunes automático"},{"label":"Permanencia","value":"Ninguna"}]'::jsonb,
    '["Activar pago automático con tarjeta o PSE.","Pausar desde Mi Cuenta antes del lunes para saltar una entrega.","Cancelación inmediata sin penalidad."]'::jsonb,
    4.7, 14, true, true,
    'Suscripción semanal botellón 19L | PH PLUS',
    'Suscripción semanal de botellón 19L con 10% de descuento permanente. Pausa o cancela cuando quieras.'
  ),
  (
    'suscripcion-trimestral',
    'Suscripción trimestral — 12 botellones programados',
    'Suscripción trimestral',
    'Tres meses cubiertos con el descuento más alto',
    'Recibe 12 botellones 19L distribuidos en 3 meses con 22% de descuento. La opción más ahorrativa del catálogo.',
    '["12 botellones 19L (228 L) distribuidos en 3 meses.","22% de descuento — la suscripción con mayor ahorro.","Frecuencia ajustable cada 7-10 días.","Cargo automático al inicio del trimestre o en 3 cuotas."]'::jsonb,
    '["22% descuento total","Frecuencia ajustable","Pago en 1 o 3 cuotas","Cancelable sin penalidad"]'::jsonb,
    '["12 botellones 19L","Acceso al panel de suscripciones","Soporte preferente"]'::jsonb,
    378000, 484000,
    'promocion', '19L', 'recargas', 53, true,
    '{"title":"MAYOR AHORRO","sub":"-22% trimestre"}'::jsonb,
    '[]'::jsonb,
    '[{"label":"Total botellones","value":"12 x 19L"},{"label":"Duración","value":"3 meses"},{"label":"Descuento","value":"22%"},{"label":"Pago","value":"1 o 3 cuotas"}]'::jsonb,
    '["Elegir frecuencia al activar la suscripción.","Pausar entregas si te vas de viaje.","Renovación automática al final del trimestre (avisamos 7 días antes)."]'::jsonb,
    4.8, 9, true, true,
    'Suscripción trimestral 12 botellones | PH PLUS',
    'Suscripción trimestral de 12 botellones 19L con 22% de descuento. La opción más ahorrativa de PH PLUS.'
  )
on conflict (slug) do nothing;
